CREATE TABLE [User](
 id VARCHAR PRIMARY KEY,
 firstName VARCHAR NOT NULL,
 lastName VARCHAR NOT NULL,
 username VARCHAR UNIQUE NOT NULL,
 password VARCHAR NOT NULL,
 email VARCHAR UNIQUE
);

CREATE TABLE Recipe(
 id VARCHAR PRIMARY KEY,
 title VARCHAR NOT NULL,
 instruction VARCHAR NOT NULL,
 cusine VARCHAR NOT NULL,
 userId VARCHAR NOT NULL,
 postedAt INTEGER NOT NULL,
 FOREIGN KEY (userId) REFERENCES [User](id) ON DELETE SET NULL
);

CREATE TABLE Ingredient(
 id VARCHAR PRIMARY KEY,
 ingredient VARCHAR NOT NULL
);

CREATE TABLE RecipeIngredient(
 recipeId VARCHAR,
 ingredientId VARCHAR,
 FOREIGN KEY (recipeId) REFERENCES Recipe(id) ON DELETE CASCADE,
 FOREIGN KEY (ingredientId) REFERENCES Ingredient(id) ON DELETE CASCADE
);

CREATE TABLE [Like](
 id VARCHAR PRIMARY KEY,
 userId VARCHAR,
 recipeId VARCHAR,
 FOREIGN KEY (recipeId) REFERENCES Recipe(id) ON DELETE CASCADE,
 FOREIGN KEY (userId) REFERENCES [User](id) ON DELETE CASCADE
);

CREATE TABLE Comment(
 id VARCHAR PRIMARY KEY,
 userId VARCHAR NOT NULL,
 recipeId VARCHAR NOT NULL,
 comment VARCHAR NOT NULL,
 postedAt INTEGER NOT NULL,
 FOREIGN KEY (recipeId) REFERENCES Recipe(id) ON DELETE CASCADE,
 FOREIGN KEY (userId) REFERENCES [User](id) ON DELETE CASCADE
);

CREATE TABLE [Group](
 id VARCHAR PRIMARY KEY,
 groupName VARCHAR NOT NULL,
 groupCreatorId VARCHAR NOT NULL,
 isPrivate BOOLEAN NOT NULL,
 groupPass VARCHAR,
 FOREIGN KEY (groupCreatorID) REFERENCES [User](id)
);

CREATE TABLE JoinGroup(
 userId VARCHAR,
 groupId VARCHAR,
 FOREIGN KEY (userId) REFERENCES [User](id) ON DELETE CASCADE,
 FOREIGN KEY (groupId) REFERENCES [Group](id) ON DELETE CASCADE
);
